name: Release Zip

on:
  release:
    types: 
      - published

jobs:
  zip-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Python
      - name: Install Python
        run: sudo apt update && sudo apt install -y python3

      # Step 3: Print the release tag

      # Step 4: Move files to a folder named OctaRender
      - name: Prepare folder structure
        run: |
          mkdir /tmp/OctaRender
          cp -r . /tmp/OctaRender

      #Step 5: Update Manifest
      - name: Update Manifest
        run: |
          cd /tmp
          python3 manifest.py --version ${{ github.ref }}
        
      # Step 6: Zip files
      - name: Zip files
        run: |
          cd /tmp
          rm -rf OctaRender/.git*
          rm -f OctaRender/README.md
          zip -r OctaRender.zip OctaRender

      # Step 7: Release
      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            /tmp/OctaRender.zip
            /tmp/OctaRender/blender_manifest.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

