name: Release Zip

on:
  release:
    types: 
      - published

jobs:
  zip-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Install Python
      - name: Install Python
        run: sudo apt update && sudo apt install -y python3

      # Step 3: Print the release tag
      - name: Print release tag
        run: python3 -c "print('${{ github.ref }}')"

      # Step 4: Move files to a folder named OctaRender
      - name: Prepare folder structure
        run: |
          mkdir /tmp/OctaRender
          cp -r . /tmp/OctaRender
          
      # Step 5: Zip files
      - name: Zip files
        run: |
          cd /tmp
          rm -rf OctaRender/.git*
          rm -f OctaRender/README.md
          zip -r OctaRender.zip OctaRender

      # Step 6: Release Zip
      - name: Upload zip to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/OctaRender.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

