name: Release Zip

on:
  release:
    types: 
      - published

jobs:
  zip-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Zip files
        run: |
          zip -r OctaRender.zip ./*

      - name: Upload zip to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: OctaRender.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
