name: Release Zip

on:
  release:
    types: 
      - published

jobs:
  zip-files:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Move files to a folder named OctaRender
      - name: Prepare folder structure
        run: |
          mkdir /tmp/OctaRender
          cp -r . /tmp/OctaRender
          
      # Step 3: Zip files
      - name: Zip files
        run: |
          cd /tmp && zip -r OctaRender.zip OctaRender

      # Step 4: Release Zip
      - name: Upload zip to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: /tmp/OctaRender.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
